services:
  data-pipeline:
    build: .
    container_name: simple_pipeline_container
    volumes:
      - ./data:/data
    environment:
      - INPUT_PATH=/data/Medicaldataset.csv
      - OUTPUT_PATH=/data/CleanedMedicalData.csv
